<?php
/**
 * @file
 * Module file
 */

/**
 * Implement hook_menu().
 */
function fbwall_menu() {

 	$items['admin/config/custom'] = array(
    'title' => 'Custom',
    'description' => 'Custom Module.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  	);

    $items['admin/config/custom/fbwall'] = array(
    'title' => 'Facebook wall',
    'description' => 'Configuration for the facebook wall module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fbwall_form'),
    'access arguments' => array('administer users'),
    'file' => 'fbwall.inc',
    );

    return $items;
}
 
/**
* Implements hook_block_info().
*/
function fbwall_block_info() {
	$blocks = array();
	
	$blocks['fbwall'] = array(
	'info' => t('fbwall block'),
	'cache' => DRUPAL_NO_CACHE,
	);
	
	return $blocks;	
}

 /**
 * Implements hook_block_view().
 */
function fbwall_block_view($block_name = '') {
	if ($block_name == 'fbwall') {	

		$settings = variable_get('fbwall_settings', '');
		
		$path = drupal_get_path('module', 'fbwall');
		drupal_add_js($path . '/js/jquery.neosmart.fb.wall.js');
		drupal_add_css($path . '/js/jquery.neosmart.fb.wall.css');	 
		drupal_add_js($path . '/js/fbwall.js');	  
		drupal_add_js(array('fbwall_settings' => $settings), 'setting');

		// Creation of the block
		$block = array(
 		'subject' => t('Facebook wall'),
 		'content' => '<div id="facebook_wall"></div>',
		);
		
		return $block; 		
	}
}

